

export enum userActionType {

    USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",

    USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",

    USER_LOGIN_FAIL = "USER_LOGIN_FAIL",

    USERS_LIST_REQUEST = "USERS_LIST_REQUEST",

    USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS",

    USERS_LIST_FAIL = "USERS_LIST_FAIL",

    USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
    USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL",

    GET_PROJECTS_OF_USER_REQUEST = "GET_PROJECTS_OF_USER_REQUEST",

    GET_PROJECTS_OF_USER_SUCCESS = "GET_PROJECTS_OF_USER_SUCCESS",

    GET_PROJECTS_OF_USER_FAIL = "GET_PROJECTS_OF_USER_FAIL",

    ASSIGN_PROJECT_REQUEST = "ASSIGN_PROJECT_REQUEST",
    ASSIGN_PROJECT_SUCCESS = "ASSIGN_PROJECT_SUCCESS",
    ASSIGN_PROJECT_FAIL = "ASSIGN_PROJECT_FAIL",
    USER_UPDATE_ADMIN_REQUEST = "USER_UPDATE_ADMIN_REQUEST",
    USER_UPATE_ADMIN_SUCCESS = "USER_UPDATE_ADMIN_SUCCESS",
    USER_UPATE_ADMIN_FAIL = "USER_UPDATE_ADMIN_FAIL",

    DELETE_USER_REQUEST = "DELETE_USER_REQUEST",

    DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS",

    DELETE_USER_FAIL = "DELETE_USER_FAIL",

    USER_INFO_REQUEST = "USER_INFO_REQUEST",

    USER_INFO_SUCCESS = "USER_INFO_SUCCESS",

    USER_INFO_FAIL = "USER_INFO_FAIL",

    USER_DELETE_REQUEST = "USER_DELETE_REQUEST",
    USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS",
    USER_DELETE_FAIL = "USER_DELETE_FAIL",

    USER_INFO_RESET = "USER_INFO_RESET",

    USER_SIGNUP_RESET = "USER_SIGNUP_RESET"


}






export enum courseActionType {

    COURSE_ASSIGN_REQUEST = "COURSE_ASSIGN_REQUEST",

    COURSE_ASSIGN_SUCCESS = "COURSE_ASSIGN_SUCCESS",

    COURSE_ASSIGN_FAIL = "COURSE_ASSIGN_FAIL",

    COURSE_DELETE_FROM_USER_REQUEST = "COURSE_DELETE_FROM_USER_REQUEST",

    COURSE_DELETE_FROM_USER_SUCCESS = "COURSE_DELETE_FROM_USER_SUCCESS",

    COURSE_DELETE_FROM_USER_FAIL = "COURSE_DELETE_FROM_USER_FAIL",

    COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST",

    COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS",

    COURSE_DELETE_FAIL = "COURSE_DELETE_FAIL",

    COURSE_NOT_ASSIGN_REQUEST = "COURSE_NOT_ASSIGN_REQUEST",

    COURSE_NOT_ASSIGN_SUCCESS = "COURSE_NOT_ASSIGN_SUCCESS",

    COURSE_NOT_ASSIGN_FAIL = "COURSE_NOT_ASSIGN_FAIL",

    ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST",

    ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS",

    ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL"

    
}


export enum alertActionType {

    SET_ALERT = "SET_ALERT",

    REMOVE_ALERT = "REMOVE_ALERT"
}